modLoader="javafml"
loaderVersion="[35,)"
license="Not specified"

[[mods]]
modId="minecraftmod"
version="1.0.0"
displayName="minecraftmod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Megaport, MCreator"

[[dependencies.minecraftmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"




